### ISSUE TITLE
Fill type and stroke type in top menu bar are empty

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/vectorpea#10]
After an expansion of the color of the fill and stroke - there aren't any default colors and types (gradient, full, pattern) like in Photopea.

**Comment by photopea** [comment]
We want Vectorpea to be familiar to the users of Illustrator. That menu is meant for Swatches (different swatches than in Photopea).

You can change these parameters at the bottom of a toolbar (set fill or stroke to none/color/gradient).
