### ISSUE TITLE
Grouping shapes with keyboard shortcut doesn't work and after that program freezes

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/vectorpea#13]
Steps to reproduce:

1. Create new document
2. Draw two shapes (rectangles)
3. Select two shapes on the layers palette with shift
4. Use ctrl+g shortcut 

Program freeze.

**Comment by photopea** [comment]
It works for me (I probably fixed it by fixing other bugs). Also, I have added Object - Group to the menu.
