### ISSUE TITLE
In radial gradient, point of the center shouldn't move outside the circle

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/vectorpea#16]
It is a very interesting feature but shouldn't work like that :D

![obraz](https://github.com/photopea/vectorpea/assets/38118273/72532b90-cc53-4e8f-8926-bafbd725bd55)

**Comment by photopea** [comment]
Ok, I have restricted it to the inner part of the ellipse :) but the focus point outside is also a valid case in SVG and PDF :) https://stackoverflow.com/questions/59694933/svg-radial-gradients-moving-focal-point-center
