### ISSUE TITLE
[BUG] Text disappears after creating a new shape

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/vectorpea#17]
Steps to reproduce:

1. Create a new document
2. With type tool draw rectangle for the paragraph 
3. write some text there
4. use any of the shape tool (rectangle or free pen) and draw a shape

Result: 
The new shape layer on the layers palette doesn't show. Instead on the text layer appears a new shape and text is missing.

**Comment by photopea** [comment]
fixed! thanks :)
