### ISSUE TITLE
[BUG] When the point in the non-closed path is selected with the direct select tool zooming out with keyboard shortcuts freezes the program

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/vectorpea#18]
Steps to reproduce:

1. Create a new document
2. Use the free pen tool
3. Draw a non-closed circle
4. switch to the Direct select tool and select the last point in the path
5. Use ctrl + alt + spacebar + left mouse button to zoom out

everything freezes

**Comment by photopea** [comment]
It is fixed now, it is related to the previous bugs.
