### ISSUE TITLE
Support for older formats?

### ISSUE THREAD

**Issue by jimbolaya** [photopea/vectorpea#19]
This falls under a feature request.

I have a lot of old drawing files. Some are TurboCAD and are only vector files and some are Micrographx Draw (which was bought by Corel at some point), which allows adding non-vector files. 

I realize this is a long shot, but let me know if there's any intention of adding additional formats like this.

**Comment by photopea** [comment]
Could you attach a few of your files here, e.g. in a ZIP archive?

**Comment by jimbolaya** [comment]
[testdrawing.zip](https://github.com/photopea/vectorpea/files/13060772/testdrawing.zip)
For a few I was able to find stuff I converted. Unfortunately, I don't have access to TurboCAD any more and I can only get the Micrografx Draw to run reliably under wine which crashes when I open a file dialog. I hope this helps.

**Comment by photopea** [comment]
Your ZIP archive contains four different files. I can open AI and DXF files in Photopea. Do you need to open DRW and TCW files in Photopea, too?

**Comment by jimbolaya** [comment]
I was hoping for DRW and TCW files. I think the AI file is an export of the DRW file since I thought it might help. Similarly I think the DXF is an export of the TCW.

Let me know if there's anything else I can provide. 

Thank you so much for looking at this. I hope you out can succeed.

**Comment by photopea** [comment]
I dont think anyone else needs to open DRW or TCW in Photopea. We should rather focus on other features. You can already open AI and DXF in Photopea, so use those.
