### ISSUE TITLE
Cannot open this PSD

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/vectorpea#21]
[Mala Leche - Rules.zip](https://github.com/photopea/vectorpea/files/13168526/Mala.Leche.-.Rules.zip)

:/

**Comment by photopea** [comment]
I have fixed it, it should work now.

One more thing: some smart objects in your PSD are PSD files. Before, when you modified these smart objects, the PSD was generated, which does not contain the preview of the final image. I changed it - update your PSD smart objects in your PSD.

Vectorpea can not re-render the PSD smart object (to get a preview), so it reads the resulting image inside the PSD file of that smart object.

**Comment by photopea** [comment]
So in short, Photopea creates a bit larger PSD files now, to make them look well in Vectorpea :)
