### ISSUE TITLE
Feature request: Option to set SVG viewBox 

### ISSUE THREAD

**Issue by zcraber** [photopea/vectorpea#22]

**Comment by photopea** [comment]
What exactly is wrong with the SVG produced at the moment?

We want Vectorpea to be familiar to users of Adobe Illustrator. How do you do this in Illustrator?

**Comment by zcraber** [comment]
> What exactly is wrong with the SVG produced at the moment?

There is no option to set viewbox.

> How do you do this in Illustrator?

Not sure about Illustrator, but in [Inkscape](https://inkscape.org/) there is this option to set the viewbox in File > Document Properties: 

![image](https://github.com/photopea/vectorpea/assets/61133303/4d64d843-bf49-4b35-b7a0-adf820c1aa39)

**Comment by photopea** [comment]
I see, I think it corresponds to Artboard properties in Adobe Illustrator.

**Comment by photopea** [comment]
Now, the viewBox is set to the total bounding box of all artboards. Usually, you have only one artboard. Press Window - Artboards, to see a list of artboards, and to edit them (enter the new size, etc).
