### ISSUE TITLE
Outline mode (Ctrl + Y)

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/vectorpea#23]
I am missing the Ctrl + Y command to preview the contour of the shapes.

Video:
https://www.youtube.com/watch?v=a53rp-PXJDY&t=287s

**Comment by rcoenen** [comment]
Yes please add. This Ai feature was never done right in Inkscape

**Comment by photopea** [comment]
I have added this feature! I don't know much about it. Currently, when you enable it, it just changes the rendering mechanism (while all tools still work the same).

**Comment by TheRadicalDreamer** [comment]
Looks good so far.

I'll report an issue if i find a bug

**Comment by rcoenen** [comment]
Works!
