### ISSUE TITLE
Unable to open this SVG in Vectorpea and Photopea

### ISSUE THREAD

**Issue by zcraber** [photopea/vectorpea#24]
[pattern_1.svg](https://github-production-user-asset-6210df.s3.amazonaws.com/61133303/280327450-d4f76653-b201-4911-a449-5ca7cb187c66.svg)

Stuck with a loading screen.

![image](https://github.com/photopea/vectorpea/assets/61133303/a2fc22b9-835a-43a0-8ec1-fa4d9c50d066)

In Photopea it appears blank.

**Comment by photopea** [comment]
Fixed both in PP and VP, thanks for reporting it! :)
