### ISSUE TITLE
"File name has to end with .psd"

### ISSUE THREAD

**Issue by jondlove** [photopea/vectorpea#25]
**Steps to Reproduce**
- File > Save More > AI to Storage
- Select "[Google Drive] Private Folder" from Sidebar
- [Connect Google Drive]
- Attempt to save file with '.ai' extension

A banner appears with the error "File name has to end with .psd", and no file is saved. 
Renaming to a .psd extension does nothing at all (no error, no file saved)

Tested On: Firefox 119.0 and Safari 17.0, on MacOS Sonoma (14.0), on Apple M1

**Comment by photopea** [comment]
Thanks for reporting it, it should be fixed now.
