### ISSUE TITLE
Position of the stroke is incorrect (inside/outside)

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/vectorpea#3]
It doubles the size of the stroke in the position: Outside and Inside.
Correct:
![obraz](https://github.com/photopea/vectorpea/assets/38118273/8b4f7769-42bc-41a7-991d-23d39ef81a59)
Bad ones:
![obraz](https://github.com/photopea/vectorpea/assets/38118273/563f4022-3feb-4fce-8da6-0cb17a99552f)
![obraz](https://github.com/photopea/vectorpea/assets/38118273/9e23c1fa-d343-45e6-b6b4-4f829c2c6694)

Browser: Chrome 118.0.5993.70
OS: Windows 10

**Comment by photopea** [comment]
Photopea (and Vectorpea) can not detect inside / outside stroke from AI files, so I will try to work on it first.

**Comment by photopea** [comment]
I spent several days looking into it, but this information is stored in AI files in a very complicated way, so I give up.

Also, the stroke position is not supported in PDF or SVG formats. When you export a PDF or an SVG in Adobe Illustrator and the stroke position is not at the center, the stroke is converted into a filled vector path.

I removed this feature from Vectorpea for now.

**Comment by MichalSZZ** [comment]
OK. I understand. That is very important feature and common used by designers.
I have my fingers crossed for implemantation (even if it will be not supported in Illustrator way - for now). Not everyone need to make AI files that will be opened in Illustrator. If you will add changing stroke to the shape - this will not be a problem for exporting to PDF.
