### ISSUE TITLE
Cannot go to Google Photos, only the Google Search viewed, but in Photos, can only be viewed

### ISSUE THREAD

**Issue by burnsboyamazing** [photopea/vectorpea#36]
What happens if you click on "Launcher" app then type in "Google Photos".
[Screen recording 2024-01-14 4.41.11 PM.webm](https://github.com/photopea/vectorpea/assets/154830140/097b6b23-16d4-401c-a93c-843701e6b163)
[Screen recording 2024-01-14 4.41.11 PM(1).webm](https://github.com/photopea/vectorpea/assets/154830140/e0e0402b-0f57-486b-b696-9aa8dec1e7ae)

**Comment by photopea** [comment]
Hi, how is it related to our website www.photopea.com? We are not Google and we can not change the way Google Photos work :(

**Comment by burnsboyamazing** [comment]
It works!

**Comment by photopea** [comment]
ok

**Comment by burnsboyamazing** [comment]
Any updates?
