### ISSUE TITLE
Problem with multiple strokes and text strokes

### ISSUE THREAD

**Issue by xchardon** [photopea/vectorpea#43]
Hello,

We have a problem with strokes when importing files from illustrator:

- Shape with multiple strokes: duplicated to several shapes with one stroke each
- Text with stroke (outline): the stroke is not shown in vectorpea

a description is shown in the pdf file attached (sorry it's in french)
[Problématiques rencontrées.pdf](https://github.com/photopea/vectorpea/files/14723319/Problematiques.rencontrees.pdf)
I can provide an illustrator file if needed (not accepted as attachment here)

**Comment by photopea** [comment]
We dont really know what is inside AI files, because Adobe did not publish any description of the AI file format. I am afraid what we have now is the best we can get :( unless you can convince Adobe to tell us how AI format works.

**Comment by photopea** [comment]
Maybe I will look into it in the future, but I am still working on Photopea and Vectorpea alone, and I decided to focus on Photopea this year, and I will look at Vectorpea next year.
