### ISSUE TITLE
Combining shapes - vectorpea

### ISSUE THREAD

**Issue by spamowe** [photopea/vectorpea#44]
We could really use a feature that allows for combining shapes. Currently, I can edit the path of a square or a circle. I'd like to be able to create more complex shapes using simple functions: combining and cutting.
For example, if I wanted to create the outline of Mickey Mouse's head, I could use three circles and join them together. Doing this manually, by modifying the path of each circle, is very frustrating.

By the way, great job! I really enjoy using your software.

**Comment by photopea** [comment]
I think it should be solved once we implement the Pathfinder: https://github.com/photopea/vectorpea/issues/31
