### ISSUE TITLE
Could not log in with Google

### ISSUE THREAD

**Issue by Alexander-Burns** [photopea/vectorpea#45]
@TheRadicalDreamer WRDSB users are having the same issue with Error 400: admin_policy_enforced in Google, interfering with Photopea.
Steps to Reproduce:
1. Open Photopea.
2. Log in with Google.
WRDSB users are not allowed to log in with Google, both Photopea and Vectorpea is the same issue. See video and screenshot.
[Screen recording 2024-04-24 14.06.31.webm](https://github.com/photopea/vectorpea/assets/113866683/aa6c7b36-6d2a-4923-b14f-2bfad94e91e8)
![Screenshot 2024-04-24 14 07 03](https://github.com/photopea/vectorpea/assets/113866683/bda07575-ba16-4eb4-96e2-ed90738d68fc)

**Comment by photopea** [comment]
What you are writing makes no sense. You should improve your AI.
