### ISSUE TITLE
Unable to create stroke or fill

### ISSUE THREAD

**Issue by realwitt** [photopea/vectorpea#46]
I'm a big fan of your software! I admire your apps a lot. 

**Steps to reproduce:**
1. Open new project
2. Create rectangle
3. Delete stroke
4. Unable to create new stroke on shape

GIF:
![2024-04-29 09 43 10](https://github.com/photopea/vectorpea/assets/63869537/3dd9dd64-90b6-4838-b339-d6294af09a81)

**Comment by photopea** [comment]
Hi, what is "create rectangle" and "delete stroke"? Your screenshot does not show a rectangle.

**Comment by realwitt** [comment]
After further testing, it seems to be for both fill and stroke.
It applies to any shape, it doesn't matter what shape it is (rectangle, square, trapezoid, octagon, etc.). 
**It seems like if you have a shape and remove the shape's stroke or fill, you are unable to create a stroke or fill for that shape.** At least I don't see a way to, maybe this is due to me not understanding the software correctly.

**Comment by photopea** [comment]
You should use the bottom of a toolbar to set the fill / stroke style.
