### ISSUE TITLE
[BUG] Program freezes after ctrl+z

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/vectorpea#5]
Steps to reproduce:

1. Open Vectorpea.com
2. Create a new, empty project
3. Draw a rectangle or line
4. use Ctrl+Z

now you can't change tool and do anything. After closing the project tab and creating a new one - it doesn't have an artboard.

Browser: Chrome 118.0.5993.70
OS: Windows 10

**Comment by photopea** [comment]
fixed, thanks!
