### ISSUE TITLE
vectorpea

### ISSUE THREAD

**Issue by n1z5** [photopea/vectorpea#50]
First, I want to ask if this is Victoropia in the basic version, is it like this, or is this just a preliminary version?
Will a tool that builds the shapes will exist؟؟

**Comment by rice7th** [comment]
I assume it will at some point. Vectorpea is still in it's early development.

**Comment by TheRadicalDreamer** [comment]
is still in BETA
More feedback we need to give, in order to have more features

**Comment by photopea** [comment]
The Shape Builder feature is already in Photopea!
