### ISSUE TITLE
Ability to measure lines

### ISSUE THREAD

**Issue by ybakesweetcandy** [photopea/vectorpea#54]
We use illustrator for the sole purpose of measuring lines, if this was possible in Photopea, then we could fully move and commit to Photopea, which we would like to

**Comment by photopea** [comment]
Hi, I have added this feature to both Photopea (Window - Vector Info) and Vectorpea (Window - Document Info).

It shows the properties of selected layers / paths, including the number of paths, lengths, etc. It shows the length in ruler units (enable rulers in View - Rulers, change the ruler unit by right-clicking the ruler).

Let me know if it works as you expected, or if there are any problems.
