### ISSUE TITLE
.ai files import at wrong sizes

### ISSUE THREAD

**Issue by Murnjendoof** [photopea/vectorpea#56]
Imported .ai files are consistently smaller than they should be. I imported a .ai file that was 32x64 pixels when exporting, but it imported as 8x15 pixels. This wouldn't be so bad if it was possible to resize the canvas, but that doesn't seem possible.

**Comment by photopea** [comment]
Hi, what about the size in inches / centimeters / millimeters, is it correct? You can change the ruler units by right-clicking them.

**Comment by Murnjendoof** [comment]
Changing the ruler units doesn't affect the size of the canvas. I'm not sure what you're trying to ask. The canvas was 32x64 pixels when I exported the file, and 8x15 pixels when I imported it.

**Comment by photopea** [comment]
Could you at least share your AI file with us?

**Comment by Murnjendoof** [comment]
Here you are. I had to zip it, since Github won't let me upload .ai files for some reason.
[Ovenplate.zip](https://github.com/user-attachments/files/16457235/Ovenplate.zip)

**Comment by photopea** [comment]
I opened your file in Adobe Illustrator. It says the width is 7.5 pixels or 1/10 of an inch.

I opened your file in Vectorpea. It says the width is 7.5 pixels or 1/10 of an inch.

What exactly makes you think that your AI should be displayed at a different size?

**Comment by Murnjendoof** [comment]
> I opened your file in Adobe Illustrator. It says the width is 7.5 pixels or 1/10 of an inch.
> 
> I opened your file in Vectorpea. It says the width is 7.5 pixels or 1/10 of an inch.
> 
> What exactly makes you think that your AI should be displayed at a different size?

When I exported it from Vectorpea, the width of the project was 32 pixels. I assumed that the problem was with importing .ai files, but if it imports into Illustrator at 7.5 pixels then I guess the problem might be with exporting, instead. Sorry for making that assumption.

**Comment by photopea** [comment]
It is a vector file, so you should not worry about pixels at all. Use inches instead. When you want to print it, you can set any resolution (any DPI). Set it as high as the printer can handle.

**Comment by Murnjendoof** [comment]
> It is a vector file, so you should not worry about pixels at all. Use inches instead. When you want to print it, you can set any resolution (any DPI). Set it as high as the printer can handle.

Admittedly I don't have much experience working with vector art, but I assumed that if I set the canvas to a certain size, then saved the project, the size of the canvas would be saved along with the project data. I'd specifically chosen the size of 32x64 pixels because it allowed me to use Vectorpea's grid function to get a 32x64 grid. Again, this wouldn't be nearly as much of an issue if I could resize the project after importing it, but I haven't been able to find a way to do that.

**Comment by photopea** [comment]
So there really was a bug, and it should be fixed now. If you create a 100x100 pixel document in Vectorpea, save it as AI and reopen it, you should still see the 100x100 pixels.

You can change the dimensions of documents by pressing Window - Artboard, and setting the size of an artboard.

**Comment by Murnjendoof** [comment]
> So there really was a bug, and it should be fixed now. If you create a 100x100 pixel document in Vectorpea, save it as AI and reopen it, you should still see the 100x100 pixels.
> 
> You can change the dimensions of documents by pressing Window - Artboard, and setting the size of an artboard.

Thank you very much.
