### ISSUE TITLE
Unable to open AI file

### ISSUE THREAD

**Issue by tf287** [photopea/vectorpea#57]
I am unable to open this .ai file (made yesterday in vectorpea) in either vectorpea or photopea:
[map.zip](https://github.com/user-attachments/files/16616698/map.zip)

Just gets stuck on this loading screen:
<img width="499" alt="loading screen" src="https://github.com/user-attachments/assets/bb175a59-4ea5-470a-932b-75b231d84c33">

Help! Thanks.

**Comment by photopea** [comment]
I can not open your file in Adobe Illustrator. If no program can open your file, Photopea will not open it either :(

**Comment by tf287** [comment]
Interesting, vectorpea generated the file and I never opened it with any other program. Thanks for trying!

**Comment by photopea** [comment]
Can you generate an AI file in Vectorpea, that is not openable in Vectorpea? It would really help us.
