### ISSUE TITLE
Can't crop artboard to content

### ISSUE THREAD

**Issue by Mario662629** [photopea/vectorpea#59]
There's no option to crop the artboard to the content, it seems like. I'm trying to make the artboard of an image the same size as the content. Basically, there's no "Object/Artboards/Fit to Artwork Bounds" option.

**Comment by photopea** [comment]
Is it a feature of Adobe Illustrator?

If you use the Arboard tool, and you resize each edge, it "snaps" to the bounding box of the content.

**Comment by Mario662629** [comment]
I can't even snap it to the bounding box of the content.

**Comment by photopea** [comment]
Could you tell me what should I do after opening www.photopea.com to see this problem? Are you using the Artboard tool?

**Comment by Mario662629** [comment]
> Could you tell me what should I do after opening [www.vectorpea.com](http://www.vectorpea.com) to see this problem? Are you using the Artboard tool?

Open any file (e.g. any EPS file from https://mediacentral.nba.com/wp-content/uploads/logos/nba/tor/Toronto_Raptors_Logos.zip), then immediately select the Artboard Tool and try to move it. It doesn't snap to the image boundaries.

**Comment by photopea** [comment]
I can not open your ZIP file :(

**Comment by Mario662629** [comment]
You’re not doing it right.
You have to extract the ZIP file, then in one of the extracted subfolders, open any of the EPS files. You don’t open it directly.

You can also download any SVG image and import that as well, not just use the files in that ZIP (that you didn’t download/open properly). Then use the Artboard Tool; watch as it doesn’t snap.

**Comment by photopea** [comment]
ok, I have added an option Object - Artboards - Fit to Artwork bounds.
