### ISSUE TITLE
[Feature Request] Allow change canvas size

### ISSUE THREAD

**Issue by moshfeu** [photopea/vectorpea#60]
Please allow to change the canvas (svg) size 

See how it's done in pixlr ediror 

https://github.com/user-attachments/assets/1cdf5978-1421-4a6b-8922-ea66341ac181

Greater Feature: let the app resize to fit the content 💪 

Another option is to allow creating a new canvas based on clipboard size so if I copy the content, I can create a new canvas and paste.

https://github.com/user-attachments/assets/7cdef6a3-d694-4676-b173-2487ebdb6c08

Thanks for a great tool!

**Comment by photopea** [comment]
You should use the artboard tool to change the artboard size. Or use Window - Artboards to enter a specific artobard size. See https://www.youtube.com/watch?v=Rt5MY4K105Y
