### ISSUE TITLE
[Feature Request] XML editor

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [photopea/vectorpea#67]
Once Vectorpea introduced this editor, it’s possible to let user access all XML data from a SVG file, and make some further improvements. This editor could have a button under the “Gallery” button, and designed as a panel that looks similar to Character, Paragraph, CSS and Gallery panels.

**Comment by photopea** [comment]
What is "XML data from SVG file"? Vectorpea is an editor of vector graphics, where you shoud use the GUI to edit your graphics. We do have an SVG export and import, but you can use Vectorpea 1000 times and never work with SVG.

**Comment by KrasnayaPloshchad** [comment]
This editor is something just like this.
![Xml_editor_popup](https://github.com/user-attachments/assets/6b8011e2-5dd2-4d56-b469-a8fad6697143)
It does not only expose internal structure of SVG but also allow users to modify manually.
