### ISSUE TITLE
[Feature Request] Options to set precision

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [photopea/vectorpea#68]
It would be nice to add additional options to customize number precision and/or transform precision, just similar to [SVGOMG](https://jakearchibald.github.io/svgomg/). This could be available at Preferences dialog, and the resulted data could be saved into various vector formats.

**Comment by photopea** [comment]
Hi, what precision are you talking about?

**Comment by KrasnayaPloshchad** [comment]
The “precision” is determined how many decimal points to be preserved for elements, for decimal points out of the number for precision, they will be rounded. For example, an element may have following values as the precision was set as 5:
```
<rect width="200.17535" height="99.77698" stroke="black" stroke-width="6.00005" fill="green"/>
```
But if you set precision as 0, its values could be:
```
<rect width="200" height="100" stroke="black" stroke-width="6" fill="green"/>
```

**Comment by photopea** [comment]
Wait, is it related to SVG files?

**Comment by KrasnayaPloshchad** [comment]
It’s less related to SVG files, but could be able to affect other vector formats. I’ve got the following PDFs:
* https://www.president.lv/lv/media/52/download?attachment
* https://www.ventspils.lv/app/uploads/2022/07/ventspils-pilsetas-logotips.pdf
* https://www.stjornarradid.is/library/04-Raduneytin/ForsAetisraduneytid/Skjaldarmerki%20%c3%ad%20RGB%20skj%c3%a1mi%c3%b0lar.pdf

After I opened file with [PDFXplorer](https://pdfxplorer.dev/), I click Pages Explorer to view the page, and click “Page Objects” button, select any object, then I see the following results in Object properties:
![图片](https://github.com/user-attachments/assets/c4dcd439-3213-47bc-8599-94aa992e391f)
![图片](https://github.com/user-attachments/assets/10dfd975-bd6e-46f3-b683-307d3e80d9fa)
![图片](https://github.com/user-attachments/assets/6cf7572c-5cae-497c-b05b-43f44fe6613c)

Alternatively, If you upload these files into this [online converter](https://tools.pdf24.org/en/convert-from-pdf), convert them as SVG, you will see the similar results when you open converted SVG with a text editor. So I believe this option could be applied not only SVG but also other vector formats.

**Comment by photopea** [comment]
So you want us to create an alternative for the "PDFXplorer" software, and call it "vectorpea"?

**Comment by KrasnayaPloshchad** [comment]
No, not for that. Look at screenshots carefully.

**Comment by photopea** [comment]
I still do not understand how can I help you. Please, be more specific.

**Comment by KrasnayaPloshchad** [comment]
@cuixiping @jfhenon Can you explain this?

**Comment by photopea** [comment]
I am closing it now. If you want a new feature in Vectorpea, you should describe it (what it does), or even make some illustration of how it should work inside our user interface.
